### ISSUE TITLE
Add flutter example

### ISSUE THREAD

**Issue by brookman** [brookman/rusty_chacha#6]

**Comment by sandeshkolte** [comment]
I would like to contribute to this project, what further steps should I follow.

**Comment by brookman** [comment]
Hi Sandesh @sandeshkolte :wave: 

Thank you very much for your interest. :smile:

Gladly! I have created some issues which I believe are required for a first stable release (see 1.0.0 milestone). Please go ahead and create a PR if you think you can contribute to one of the issues. For this issue I imagine to have something similar in packages/rusty_chacha/example/lib/main.dart as in the README.md. A basic Flutter app without any UI is fine I guess.

I'm currently working on the dynamic linking issue.

If you have ideas or suggestions for features and improvements feel free to open new issues.

**Comment by brookman** [comment]
Added a simple example
